### PR TITLE
Change semester command

### PR DESCRIPTION
**Pull request by amitrahman1026**

### CODE REVIEW

**Review by kohnh — COMMENTED** [review]
Maybe you can use the InvalidSemesterException that you created if the semester entered is not valid?

**Comment by amitrahman1026** [comment]
> Maybe you can use the InvalidSemesterException that you created if the semester entered is not valid?

Will utilise the exception in a future PR after discussion on standerdising error handling structure!

**Review by deenliong — COMMENTED** [review]
for isValidSemester, there can be sem 3 and 4, indicating Special Term 1 and 2 respectively

**Review by owenl131 — CHANGES_REQUESTED** [review]

**Comment by owenl131** [comment]
Can add it to the text-ui-tests

**Review by owenl131 — APPROVED** [review]
LGTM

**Pull request merged**
